namespace WebApplication2.Models
{
	public class MTerceros
	{
		public string? COD_TER { get; set; }
		public string? NOM_TER { get; set; }
		public string? DIR1 { get; set; }
		public string TEL1 { get; set; }
		public string FAX1 { get; set; }
		public string EMAIL { get; set; }
		public string? FEC_ING { get; set; }
		public string? CIUDAD { get; set; }
		public string TIP_PRV { get; set; }
		public string COD_ACT { get; set; }
		public string COD_CLA { get; set; }
		public string INT_MORA { get; set; }
		public string DIA_PLAZ { get; set; }
		public string ESTADO { get; set; }
		public string POR_DES { get; set; }
		public string AUT_RET { get; set; }
		public string POR_ICA { get; set; }
		public string REPRES { get; set; }
		public string CTA_BAN { get; set; }
		public string CLASIFIC { get; set; }
		public string COD_CAN { get; set; }
		public string COD_VEN { get; set; }
		public string POR_COM { get; set; }
		public string IND_SUC { get; set; }
		public string IND_CRED { get; set; }
		public string IND_RETE { get; set; }
		public string CTA { get; set; }
		public string CUPO_CXP { get; set; }
		public string CUPO_CXC { get; set; }
		public string I_CUPOCP { get; set; }
		public string I_CUPOCC { get; set; }
		public string COD_ZONA { get; set; }
		public string BLOQUEO { get; set; }
		public string IND_RET { get; set; }
		public string COD_BOD { get; set; }
		public string IND_MAYOR { get; set; }
		public string APL1 { get; set; }
		public string APL2 { get; set; }
		public string NOM1 { get; set; }
		public string NOM2 { get; set; }
		public string RAZ { get; set; }
		public string DIR { get; set; }
		public string DPTO { get; set; }
		public string MUN { get; set; }
		public string TIP_PERS { get; set; }
		public string DV { get; set; }
		public string TDOC { get; set; }
		public string COD_CIU { get; set; }
		public string OBSERV { get; set; }
		public string CONT_CXC { get; set; }
		public string EXTEN { get; set; }
		public string DEPA { get; set; }
		public string CONTA { get; set; }
		public string CARGO { get; set; }
		public string CEL { get; set; }
		public string PAIS { get; set; }
		public string RTIVA { get; set; }
		public string RTICA { get; set; }
		public string PREC_REM { get; set; }
		public string LISTA_PREC { get; set; }
		public string IND_IVA { get; set; }
		public DateTime FEC_NAC { get; set; }
		public string CONTACTO { get; set; }
		public string CONT_TEL { get; set; }
		public string I_PUNTOS { get; set; }
		public string COD_PAIS { get; set; }
		public DateTime FEC_MINIS { get; set; }
		public string COD_DIST { get; set; }
		public string COD_EST { get; set; }
		public string TEL { get; set; }
		public string MAIL_CONYU { get; set; }
		public string NUM_HIJOS { get; set; }
		public string PARENTEZCO { get; set; }
		public string NOM_CONYUG { get; set; }
		public string ID_CONYUGE { get; set; }
		public string EST_CIVIL { get; set; }
		public string BARRIO { get; set; }
		public DateTime FEC_FALLE { get; set; }
		public DateTime FECHA_LICE { get; set; }
		public DateTime FECHA_IPUC { get; set; }
		public string SEXO { get; set; }
		public string LUGAR_NACI { get; set; }
		public string COD_LICE { get; set; }
		public string COD_CLASE { get; set; }
		public string CONGREGA { get; set; }
		public DateTime FEC_APORT { get; set; }
		public DateTime FEC_EXPCC { get; set; }
		public string LUGAR_EXPCC { get; set; }
		public string EMAIL_FACT { get; set; }
		public string COD_ACTIV { get; set; }
		public string RESPON { get; set; }
		public string REGIMEN { get; set; }
		public string MATRICULA { get; set; }
		public string CODIMPUESTO { get; set; }
		public string CODPOSTAL { get; set; }
		public string CTA_ICAP { get; set; }
		public string CTA_ICAC { get; set; }
		public string EMAIL_FAC { get; set; }
	}
}
